# Scraping top 5 Wikipedia movie website

In [1]:
import csv
import pandas as pd
import requests
import bs4

In [2]:
res = requests.get("https://en.wikipedia.org/wiki/Tenet_(film)")
res1 = requests.get("https://en.wikipedia.org/wiki/Bad_Boys_for_Life")
res2 = requests.get("https://en.wikipedia.org/wiki/Dolittle_(film)")
res3 = requests.get("https://en.wikipedia.org/wiki/A_Little_Red_Flower")
res4 = requests.get("https://en.wikipedia.org/wiki/Godzilla_vs._Kong")

In [3]:
soup = bs4.BeautifulSoup(res.text,"lxml")
soup1 = bs4.BeautifulSoup(res1.text,"lxml")
soup2 = bs4.BeautifulSoup(res2.text,"lxml")
soup3 = bs4.BeautifulSoup(res3.text,"lxml")
soup4 = bs4.BeautifulSoup(res4.text,"lxml")

In [4]:
print("1'ST MOVIE\n")
#title
title1 = soup.select("title")[0].getText()
print("Movie name: ",title1[0:5])
#Director
for item1 in soup.select(".infobox-data")[0]:
    print("Director name: ",item1.text)
#Year of release
for year1 in soup.select(".infobox-data")[9]:
    print("Year of release:",year1.text[12:16])
#Overall gross rating
gross1 =soup.select(".infobox-data")[14].get_text()
print("Overall gross rating:",gross1[0:14])
#The cast
cast1 = soup.select(".infobox-data")[3].get_text()
print("Cast:",cast1.split("\n"))

print("\n")
print("2'ND MOVIE\n")

#title
title2 = soup1.select("title")[0].getText()
print(title2[0:18])
#Director
for item2 in soup1.select(".infobox-data")[0]:
    print("Director name: ",item2.text)
#Year of release
for year2 in soup1.select(".infobox-data")[11]:
    print("Year of release:",year2.text[12:17])
#Overall gross rating
gross2 = soup1.select(".infobox-data")[16].get_text()
print("Overall gross rating:",gross2[0:14])
#The cast
cast2 = soup1.select(".infobox-data")[5].get_text()
print("Cast:",cast2.split("\n"))
print("\n")

print("3'RD MOVIE\n")

#title
title3 = soup2.select("title")[0].getText()
print("Movie name: ",title3[0:5])
#Director
for item3 in soup2.select(".infobox-data")[0]:
    print("Director name: ",item3.text)
#Year of release
for year3 in soup2.select(".infobox-data")[11]:
    print("Year of release:",year3.text[12:17])
#Overall gross rating
gross3 =soup2.select(".infobox-data")[16].get_text()
print("Overall gross rating:",gross3[0:14])
#The cast
cast3 = soup2.select(".infobox-data")[5].get_text()
print("Cast:",cast3.split("\n"))
print("\n")

print("4'TH MOVIE\n")
#title
title4 = soup3.select("title")[0].getText()
print("Movie name: ",title4[0:10])
#Director
for item4 in soup3.select(".infobox-data")[0]:
    print("Director name: ",item4.text)
#Year of release
for year4 in soup3.select(".infobox-data")[11]:
    print("Year of release:",year4.text[13:19])
#Overall gross rating
gross4 =soup3.select(".infobox-data")[-1].get_text()
print("Overall gross rating:",gross4[0:12])
#The cast
cast4 = soup3.select(".infobox-data")[7].get_text()
print("Cast:",cast4.split("\n"))
print("\n")

print("5'TH MOVIE\n")

#title
title5 = soup4.select("title")[0].getText()
print("Movie name: ",title5[0:18])
#Director
for item5 in soup4.select(".infobox-data")[0]:
    print("Director name: ",item5.text)
#Year of release
for year5 in soup4.select(".infobox-data")[11]:
    print("Year of release:",year5.text[10:16])
#Overall gross rating
gross5 =soup4.select(".infobox-data")[17].get_text()
print("Overall gross rating:",gross5[10:14])
#The cast
cast5 = soup4.select(".infobox-data")[5].get_text()
print("Cast:",cast5.split("\n"))

1'ST MOVIE

Movie name:  Tenet
Director name:  Christopher Nolan
Year of release: 2020
Overall gross rating: $363.7 million
Cast: ['', 'John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Dimple Kapadia', 'Michael Caine', 'Kenneth Branagh', '']


2'ND MOVIE

Bad Boys for Life
Director name:  Adil & Bilall
Year of release:  2020
Overall gross rating: $426.5 million
Cast: ['', 'Will Smith', 'Martin Lawrence', 'Paola Núñez', 'Vanessa Hudgens', 'Alexander Ludwig', 'Charles Melton', 'Kate del Castillo', 'Nicky Jam', 'Joe Pantoliano', '']


3'RD MOVIE

Movie name:  Dolit
Director name:  Stephen Gaghan
Year of release:  2020
Overall gross rating: $251.4 million
Cast: ['', 'Robert Downey Jr.', 'Antonio Banderas', 'Michael Sheen', 'Harry Collett', 'Emma Thompson', 'Rami Malek', 'John Cena', 'Kumail Nanjiani', 'Octavia Spencer', 'Tom Holland', 'Ralph Fiennes', 'Selena Gomez', 'Marion Cotillard', 'Kasia Smutniak', '']


4'TH MOVIE

Movie name:  A Little R
Director name:  送你一朵小紅花
Year of release:  2020
Overall gross rating: $216 million
Cast: ['', 'Jackson Yee', 'Haocun Liu', 'Yuanyuan Zhu', 'Yalin Gao', '']


5'TH MOVIE

Movie name:  Godzilla vs. Kong
Director name:  Adam Wingard
Year of release:  2021
Overall gross rating: 2021
Cast: ['', 'Alexander Skarsgård', 'Millie Bobby Brown', 'Rebecca Hall', 'Brian Tyree Henry', 'Shun Oguri', 'Eiza González', 'Julian Dennison', 'Lance Reddick', 'Kyle Chandler', 'Demián Bichir', '']

In [16]:
#Creating csv file
df = pd.DataFrame(columns=['Title','Movie_1', 'Movie_2','Movie_3','Movie_4','Movie_5'])
df.to_csv('scrapy.csv', index=False)

**1'st Method of adding rows using dict function**

In [19]:

from csv import DictWriter
# List 
List=["Movie Name",title1[0:5],title2[0:18],title3[0:5],title4[0:10],title5[0:18]]
  
# list of column names 
field_names = ['Title','Movie_1','Movie_2','Movie_3',
               'Movie_4','Movie_5']
  
# Dictionary
dict={'Title':'Movie Name','Movie_1':title1[0:5],'Movie_2':title2[0:18],'Movie_3':title3[0:5],
      'Movie_4':title4[0:10],'Movie_5':title5[0:18]}

print(dict)
# Open your CSV file in append mode
# Create a file object for this file
with open('scrapy.csv', 'a',encoding="utf-8") as f_object:
      
    # Pass the file object and a list 
    # of column names to DictWriter()
    # You will get a object of DictWriter
    dictwriter_object = DictWriter(f_object, fieldnames=field_names)
  
    #Pass the dictionary as an argument to the Writerow()
    dictwriter_object.writerow(dict)
  
    #Close the file object
    f_object.close()
"""

{'Title': 'Movie Name', 'Movie_1': 'Tenet', 'Movie_2': 'Bad Boys for Life ', 'Movie_3': 'Dolit', 'Movie_4': 'A Little R', 'Movie_5': 'Godzilla vs. Kong '}

**2'nd Method of adding data**

In [35]:
k = "Cast"
a = cast1.split("\n")
b= cast2.split("\n")
c= cast3.split("\n")
d = cast4.split("\n")
e = cast5.split("\n")

In [24]:
from csv import writer
  
# List 
List=[k,a,b,c,d,e]
  
# Open our existing CSV file in append mode
# Create a file object for this file
with open('scrapy.csv', 'a',encoding="utf-8") as f_object:
  
    # Pass this file object to csv.writer()
    # and get a writer object
    writer_object = writer(f_object)
  
    # Pass the list as an argument into
    # the writerow()
    writer_object.writerow(List)
  
    #Close the file object
    f_object.close()

In [37]:
df = pd.read_csv("scrapy.csv")

In [38]:
df

,Title,Movie_1,Movie_2,Movie_3,Movie_4,Movie_5
0,Movie Name,Tenet,Bad Boys for Life,Dolit,A Little R,Godzilla vs. Kong
1,Director,Christopher Nolan,Adil & Bilall,Stephen Gaghan,送你一朵小紅花,Adam Wingard
2,YearOfRelease,2020,2020,2020,2020,2021
3,GrossEarned,$363.7 million,$426.5 million,$251.4 million,$216 million,2021
4,Cast,"['', 'John David Washington', 'Robert Pattinso...","['', 'Will Smith', 'Martin Lawrence', 'Paola N...","['', 'Robert Downey Jr.', 'Antonio Banderas', ...","['', 'Jackson Yee', 'Haocun Liu', 'Yuanyuan Zh...","['', 'Alexander Skarsgård', 'Millie Bobby Brow..."